language: scala

git:
  depth: false # Avoid sbt-dynver not seeing the tag

env:
  global:
    - secure: "secretkey"
  matrix:
    - TRAVIS_JDK=11

before_install:
  - curl --version # for debug purpose
  
install: java -Xmx32m -version

stages:
  - test

jobs:
  include:
    - stage: test
      script: sbt clean coverage test coverageReport
      workspaces:
        use: published-local

cache:
  directories:
    - "$HOME/.cache/coursier"
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba"
    - "$HOME/.sbt"

before_cache:
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
