version: '3'

volumes:
  mongodb_data: {}

services:
  mongodb:
    image: mongo:4.4.3
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongodb-network
    volumes:
      - mongodb_data:/data/db
networks:
  mongodb-network:
    driver: bridge